name: NPM Publish Dev
description: Publish an npm package appending timestamp and commit sha to current version

inputs:
  access:
    description: Visibility of package, allowed values are 'null', 'public' and 'restricted'
    required: false
    default: "null"
  node-version:
    description: Node version used to install and publish the package
    required: false
    default: "lts/*"
  npm-token:
    description: NPM access token used to publish the package to the npm registry
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
    - shell: bash
      run: |
        npm ci
        npm version --no-git-tag-version $(npm pkg get version | xargs)-$(date +%s)-${{ github.sha }}
        npm publish --tag ${{ github.ref_name }} --access ${{ inputs.access }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
